version: "3.9"
services:
  api:
    #image: "d0ckmg/free-gpt4-web-api:latest"
    build: .
    ports:
      - "5500:5500"
    command: --remove-sources --provider You --cookie-file /app/src/data/cookies.json --enable-telegram-bot --enable-gui --password admin123
    #command: --remove-sources